### ISSUE TITLE
Another project to add

### ISSUE THREAD

**Issue by romainl** [golanlevin/shelters-as-artworks#1]
Two guys living for some time in a shed they built in an empty place found under Copenhagen's central station: https://www.youtube.com/watch?v=xr3GV2ZLHDI

Here is a two-parts video giving a bit of background:

- https://www.youtube.com/watch?v=OTMK14w2u88
- https://www.youtube.com/watch?v=w26BruCSYnM

Thank you for this list.

**Comment by golanlevin** [comment]
Hi @romainl, thanks for posting an issue. IF you can format your suggestion so that it matches the style of my document, THEN I will take submissions. I would require the following:

* Name of the artists (not "two guys")
* Title of the artwork or project
* Year that it was done
* One single link that is the most representative or best documentation
* Brief description of what it is, with an emphasis on why it's interesting
* PNG or JPG Image, ~1000 pixels wide. 

Unfortunately I don't have any additional time to dedicate to working on this, which is why I request the above. In the case of the specific project you mention, I don't have time to watch three YouTube videos and select a good image. Also, solely from the description you provided, I can't determine what is interesting about what they did; it just sounds like two homeless guys living in a subway station.

Thanks for your help,
Golan Levin

**Comment by romainl** [comment]
Well, I don't have time for that either.
